[build]

command = "npm run prod"
publish = "build_production"
environment = { PHP_VERSION = "7.4" }

[dev]
framework = "#auto"
command = "npm run watch"
publish = "build_local"
environment = { PHP_VERSION = "8.0" }
