[build]

command = "npm run prod"
publish = "build_production"
environment = { PHP_VERSION = "8.1" }

[dev]
framework = "#auto"
command = "npm run watch"
publish = "build_local"
environment = { PHP_VERSION = "8.1" }
